Traceback (most recent call last):
  File "/home/vm/lakh_midi_dataset/.venv/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vm/lakh_midi_dataset/.venv/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/vm/lakh_midi_dataset/.venv/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vm/lakh_midi_dataset/.venv/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/vm/lakh_midi_dataset/.venv/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/vm/lakh_midi_dataset/.venv/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/vm/lakh_midi_dataset/.venv/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# run dataset profiling
profile = ProfileReport(track_df, progress_bar=False)
profile.to_notebook_iframe()
1/0
------------------

----- stderr -----
  0%|                                       | 0/40 [00:00<?, ?it/s]
----- stderr -----
  2%|â–Š                              | 1/40 [00:03<02:10,  3.36s/it]
----- stderr -----
 42%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Š                 | 17/40 [00:03<00:03,  5.89it/s]
----- stderr -----
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 40/40 [00:03<00:00, 10.39it/s]
----- stderr -----

------------------

[31m---------------------------------------------------------------------------[39m
[31mZeroDivisionError[39m                         Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[4][39m[32m, line 4[39m
[32m      2[39m profile = ProfileReport(track_df, progress_bar=[38;5;28;01mFalse[39;00m)
[32m      3[39m profile.to_notebook_iframe()
[32m----> [39m[32m4[39m [32;43m1[39;49m[43m/[49m[32;43m0[39;49m

[31mZeroDivisionError[39m: division by zero

